### ISSUE TITLE
toJson not returning results

### ISSUE THREAD

**Issue by keithslater** [Edujugon/laravel-google-ads#10]
I am trying to return the results as json by doing

    return $results->items()->toJson();

However, it is returning an empty json object.

**Comment by Edujugon** [comment]
Items is a collection of the entries from the query to the a adwords service.
I think it's not a package issue but it's simply that there is not result for that query.

**Comment by keithslater** [comment]
When I dd($results->items()). There are results.

> Illuminate\Support\Collection Object
(
    [items:protected] => Array
        (
            [0] => Google\AdsApi\AdWords\v201710\cm\Campaign Object
                (
                    [id:protected] => 1030742633
                    [campaignGroupId:protected] => 
                    [name:protected] => Campaign 1
                    [status:protected] => PAUSED
                    [servingStatus:protected] => SERVING
                    [startDate:protected] => 
                    [endDate:protected] => 
                    [budget:protected] => Google\AdsApi\AdWords\v201710\cm\Budget Object
                        (
                            [budgetId:protected] => 
                            [name:protected] => 
                            [amount:protected] => 
                            [deliveryMethod:protected] => 
                            [referenceCount:protected] => 
                            [isExplicitlyShared:protected] => 
                            [status:protected] => 
                        )

>  [conversionOptimizerEligibility:protected] => 
                    [adServingOptimizationStatus:protected] => 
                    [frequencyCap:protected] => 
                    [settings:protected] => 
                    [advertisingChannelType:protected] => 
                    [advertisingChannelSubType:protected] => 
                    [networkSetting:protected] => 
                    [labels:protected] => 
                    [biddingStrategyConfiguration:protected] => 
                    [campaignTrialType:protected] => 
                    [baseCampaignId:protected] => 
                    [forwardCompatibilityMap:protected] => 
                    [trackingUrlTemplate:protected] => 
                    [urlCustomParameters:protected] => 
                    [vanityPharma:protected] => 
                    [selectiveOptimization:protected] => 
                )

        )

)

**Comment by Edujugon** [comment]
Interesting, let me have a deeper look...

**Comment by Edujugon** [comment]
Hi @keithslater ,

Checking the result you pasted, the Google\AdsApi\AdWords\v201710\cm\Campaign object doesn't have any public property so that's why json_encode function returns "nothing".

In order to achieve so, you'll have to loop over all items and build that desired format by yourself..

**Comment by keithslater** [comment]
Got it, thanks.
