### ISSUE TITLE
Function ("query") is not a valid method for this service

### ISSUE THREAD

**Issue by keithslater** [Edujugon/laravel-google-ads#11]
I'm getting this error when trying to call some of the services

   Function ("query") is not a valid method for this service

Specifically it happens with CustomerService and ManagedCustomerService. I'm doing the following -

`$results = $this->ads->service(CustomerService::class)
            ->select(['CustomerId'])
            ->get();`

Is there something I'm doing wrong here?

**Comment by Edujugon** [comment]
Hi @keithslater ,
Sorry for the delay in reply.

The service you are using doesn't work with this package api. Hopefully I'll add it in further releases.
In the mean time, this code snippet may help you on retrieving customer. I'm using google ads API itself:

```php
$page = $this->ads->service(CustomerService::class)->getService()->getCustomers();

foreach ($page as $item) {
        var_dump($item->getDescriptiveName() . ' - ' . $item->getCustomerId() );
}
```

You always can use Google Ads API if desired. Just call the `getService()`method and from there you are playing around with google-ads api :)

Hope this helps.

**Comment by keithslater** [comment]
Yep that should work for now. Thanks.
