### ISSUE TITLE
Usage for Multiple accounts

### ISSUE THREAD

**Issue by saifabbasi** [Edujugon/laravel-google-ads#14]
Hi,

I have configured and using this API successfully for single account associated with an MCC account. However there is no example given and also i have tried multiple ways to associate my other clients through Oauth and use there token to get their client customer id, but I am getting permission error. Can you give me an example for this? or where I am missing?

**Comment by Edujugon** [comment]
Hi @saifabbasi ,
Have you tried to update the credentials data via methods:
```php
$ads->oAuth([
        'clientId' => 'test',
        'clientSecret' => 'test',
        'refreshToken' => 'TEST'
    ])
    ->session([
        'developerToken' => 'token',
        'clientCustomerId' => 'id'
    ]);
```

**Comment by saifabbasi** [comment]
Hi Marcos,

Thanks for your prompt response. I am associating users via google Oauth, in its response I am getting refresh token and access token only. So I am confused what would be the values for
'clientId' => 'test',
 'clientSecret' => 'test',
'clientCustomerId' => 'id'

in above case. Should I provide My App's developer account credentials? or MCC account? or From google's Oauth response I can get those values also for associating user?

**Comment by Edujugon** [comment]
Hi @saifabbasi ,
`clientCustomerId` should be your Adwords account customer id. When you are logged in adwords have a look at the top right corner, it should be shown there...

For the others, have a look at [this guide](https://developers.google.com/adwords/api/docs/guides/authentication#webapp). So in short, you have to create an AdWords API client app to access your AdWords account without having to handle or store the user's login info..

Hope that helps :)

**Comment by saifabbasi** [comment]
Hi Marcos,
My scenario is I am providing users a dashboard to fetch and see their adwords data in my app. So I can only have there Oauth credentials initially. How can I get their clientcustomerID, even their account are not managed by me. This is possible as i have created an account with www.geckoboard.com, and tried to add an adwords account with them. I have only authenticated through Oauth, but they ave fetched my clientcustomerid and tan data with the help of it.  So I just want to know is there any method from which we can provide Oauth details of a new customer/user and it can fetch clientcustomerid from adwords account, providing My app has a verified scope to work with adwords API? and I have listed an example URL above where same functionality can be seen.

Thanks,

Saif

**Comment by Edujugon** [comment]
Hi @saifabbasi ,

These days are quite busy, that's why I couldn't reply before..

I'll provide you with a code snippet where you can get exactly what you need.

Bear with me since it can take me untill tomorrow..

**Comment by Edujugon** [comment]
Hi @saifabbasi ,

As promised, here is the example. Before this can work, you must update to the latest package version (1.4.0)

```php
$adWordsServices = new GoogleAds();

//Build the session
$session = (new AdwordsSession())->buildWithOAuth($developerToken,$userRefreshCredentials);

//Get customer service
$managedCustomerService = $adWordsServices->service(CustomerService::class,$session)->getService();

$page = $managedCustomerService->getCustomers();

foreach ($page as $item) {
  var_dump($item->getDescriptiveName() . ' - ' . $item->getCustomerId() );
}
```

Don't forget to put the use statements at the top of the class
```php
use Edujugon\GoogleAds\Session\AdwordsSession;
use Google\AdsApi\AdWords\v201710\mcm\CustomerService;
```

Also make sure that your `userRefreshCredentials` is an instance of `\Google\Auth\Credentials\UserRefreshCredentials`

The above snippet, would show all Customer names and customerIds related to that OAuth instance.

I'm planning to make it a bit easier in future releases but I think that solve what you wanna achieve.

Hope that helps

**Comment by saifabbasi** [comment]
Hi,
Thanks for detailed reply. Now you got that what I wanted to do. Very
helpful.

Thanks alot

**Comment by gezimapi** [comment]
hi 

i have to tried to list the accounts in my mcc using:

use Edujugon\GoogleAds\GoogleAds;
use Google\AdsApi\AdWords\v201809\mcm\CustomerService;
use Edujugon\GoogleAds\Session\AdwordsSession;

        $userRefreshCredentials = [
            'clientId' => config('google-ads.production.clientId'),
            'clientSecret' => config('google-ads.production.clientSecret'),
            'refreshToken' => config('google-ads.production.refreshToken')
        ];

 $adWordsServices = new GoogleAds();
 $session = (new AdwordsSession())->buildWithOAuth(config('google-ads.production.developerToken'),$userRefreshCredentials);

$managedCustomerService = $adWordsServices->service(CustomerService::class, $session)->getService();
 $page = $managedCustomerService->getCustomers();

i get this response:

Argument 1 passed to Google\AdsApi\AdWords\AdWordsSessionBuilder::withOAuth2Credential() must implement interface Google\Auth\FetchAuthTokenInterface, array given, called in /home/glanaj/projects/neon/vendor/edujugon/laravel-google-ads/src/src/Session/AdwordsSession.php on line 90
