### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by phillipmadsen** [Edujugon/laravel-google-ads#15]
```
Google \ AdsApi \ AdWords \ v201708 \ cm \ ApiException
[QuotaCheckError.INVALID_TOKEN_HEADER @ ; trigger:'token']
```
Can you tell me what im doing wrong?

**Comment by Edujugon** [comment]
Hi @phillipmadsen ,

That error normally happens when the developer token in the request is missing or invalid.

Ensure that a developer token has been set and matches the value in the AdWords API Center.

**Comment by Edujugon** [comment]
Closing this issue since there isn't any update from the creator.

Feel free to reopen it if necessary.
