### ISSUE TITLE
Assistance Please

### ISSUE THREAD

**Issue by laravelcoder** [Edujugon/laravel-google-ads#17]
Getting this error
```
Client error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `401 Unauthorized` response: { "error": "invalid_client", "error_description": "The OAuth client was not found." }
```
When i try to use the developer and test info for testing while i wait for my developer token to be approved that is the error i am getting now. 

my config looks like this for test. 
```
return [
	'env' => 'test',
	//Google Ads
	'production' => [],
	'test' => [
		'developerToken' => "token",
		'clientCustomerId' => "id",
		'userAgent' => "LARADA SCIENCES",
		'clientId' => "id",
		'clientSecret' => "test",
		'refreshToken' => "Test"
	],
	'oAuth2' => [
		'authorizationUri' => 'https://accounts.google.com/o/oauth2/v2/auth',
		'redirectUri' => 'urn:ietf:wg:oauth:2.0:oob',
		'tokenCredentialUri' => 'https://www.googleapis.com/oauth2/v4/token',
		'scope' => 'https://www.googleapis.com/auth/adwords'
	]
];


```
Any help would be appreciated.

**Comment by Edujugon** [comment]
Hi @laravelcoder ,

Invalid client means that the client id or the client secret that you are using are not valid. They must be the ones you have taken from Google Developer console.

Make sure you're using the valid ones and try again

**Comment by Edujugon** [comment]
Closing this since there is no response from the issue creator.

Feel free to reopen it if needed.

**Comment by MamoonaShuja** [comment]
I am using correct credentials still same issue
