### ISSUE TITLE
Fatal Exception - unexpected 'list' (T_LIST)

### ISSUE THREAD

**Issue by reneras** [Edujugon/laravel-google-ads#2]
Hi Eduardo!

Thanks for your great work. I just dropped it in a new project using homestead 5.4.0.
After setting up the config and generating the token successfully, I run into an error after calling just this line:

`$ads = new GoogleAds();`

This is the error:

Could it be a Laravel version mismatch ?

```
(1/1) FatalErrorException
syntax error, unexpected 'list' (T_LIST)
in GoogleAds.php (line 168)
at FatalErrorException->__construct()
in HandleExceptions.php (line 134)
at HandleExceptions->fatalExceptionFromError()
in HandleExceptions.php (line 119)
at HandleExceptions->handleShutdown()
in HandleExceptions.php (line 0)
at Composer\Autoload\includeFile()
in ClassLoader.php (line 322)
at ClassLoader->loadClass()
in Controller.php (line 28)
at spl_autoload_call()
in Controller.php (line 28)
at HomeController->show()
in Controller.php (line 55)
```

**Comment by Edujugon** [comment]
Hi @reneras :)

I've just run all the tests and they pass...
It's weird that you get that error just running  `$ads = new GoogleAds();` since the constructor isn't related to that error line...

In order to be able to replicate the issue, could you let me know on what php version you are running the code and the laravel version?

**Comment by reneras** [comment]
Sure. The laravel version is 5.4 and the php version PHP 7.1.3-3+deb.sury.org~xenial+1 ( from the vagrantbox laravel/homestead 5.4.0 )

The code:

```
<?php

namespace App\Http\Controllers;

use Edujugon\GoogleAds\GoogleAds;

class HomeController extends Controller
{
    public function show()
    {
        $ads = new GoogleAds();
        return view('home');
    }
}
```

**Comment by Edujugon** [comment]
What package version are you using? the last one?

**Comment by reneras** [comment]
I've solved the issue. 

Renaming two functions, both named "list()", to anything not reserved by PHP resolved the issue.

GoogleAds.php 168: `ReportTypes::returnList();`
GoogleAds.php 177: `Format::returnList();`

Also changed their names in the class files ReportTypes and Format. 
Then the exception went away.

**Comment by Edujugon** [comment]
Cool!
I'll check it out and update it for the future releases :)

I'm closing the issue since it's been solved.
