### ISSUE TITLE
Please update to a new version of adwords ?

### ISSUE THREAD

**Issue by nmfarshad** [Edujugon/laravel-google-ads#20]
I get this error 
`Details: [fieldPath: ; trigger: You are accessing an AdWords API version v201708 that has been discontinued. Calls to this version may fail. Please visit the AdWords API blog for information on migration to the new AdWords API version.; errorString: RequestError.UNSUPPORTED_VERSION]`

**Comment by Edujugon** [comment]
Hi @nmfarshad ,
What version of the package are you using?
The latest version is supporting services above the mentioned above, you can use "v201710".

Anyway, I'm planning to upgrade the adwords dependency version to the last one soon...

**Comment by Edujugon** [comment]
Hi @nmfarshad ,

This is  a follow-up to see if you fixed the issue using the version (v201710) I suggested in my previous comment.

**Comment by zesda** [comment]
I'm going to second this, [sunset for v201710 is 11th July](https://developers.google.com/adwords/api/docs/sunset-dates). 

Ideally we're going to need something more recent before then so we can test on staging environments?

**Comment by Edujugon** [comment]
Hi @nmfarshad @zesda ,

I've just released a new version (1.5.0) with the latest google ads version.
