### ISSUE TITLE
Question on not using the php artisan googleads:token:generate command

### ISSUE THREAD

**Issue by CarlosSR** [Edujugon/laravel-google-ads#21]
Hi, I'm was trying to use the console command for getting the refresh token but I was always getting errors about the "token redeemed". I always used new Authorization code, following all the process again just like this https://developers.google.com/adwords/api/docs/guides/authentication#configure_and_use_a_client_library 

But then I realized that I was trying to generate a refresh token... but the OAuth 2.0 Playground site was generating it by the console.. SO, I went, take that refresh token and put it on the google-ads.php file... so it seems to work, the only issue is that now when I'm trying to make a request via Laravel controller, just like your examples, I get this

[QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'<null>']

I have to say that this might be truth because on the API Center of the agency's adwords account appear this (test account... )

Nivel de acceso
Cuenta de prueba
Solicitar acceso básico
open_in_new
 
It means... that the output of my Laravel app could be truth... what do you think? 

Any ideas? should I use only the command for generate the refresh toke? thanks a lot in advanced for your help. (Sorry about the syntaxis)

**Comment by Edujugon** [comment]
Hola @CarlosSR ,

Well, that error basically means that you are using an unapproved developer token to make calls against a production account.

Have a look at [this link](https://developers.google.com/adwords/api/docs/common-errors#QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED) to get more details.

Regarding the Fresh token, It's ok if you don't generate it via console as long as it is a valid one.

Hope this helps.

**Comment by CarlosSR** [comment]
Exactly. I'm doing this in my job. We all use the G suite for mailing. So, we have a main account using adwords and I have mine linked to this, and I'm using their developer token... I think I must figure it out with all those permissions and stuff. Anyway, thanks a lot for the package and the help! Saludos desde la Ciudad de México.

**Comment by Edujugon** [comment]
Cool!
Just let me know if face any further issue :)

Saludos!!

**Comment by CarlosSR** [comment]
Finally I don't have that error. I was putting the ID client of the "main" account, a MCC I guess. I have never found my own client ID on console.developers.google.com but they send me an email in order to make me pay for a campaign and there was the fantastic client ID. Mine.

But now I'm wondering if I'm really making the conection. This is what appears when I make the first sample query in your documentation, but that request doesn't shows on my developers console. :( 

I have to say that I'm using the google OAuth2 playground, could be that I have missed something?

![captura de pantalla 2018-04-24 a la s 12 56 15](https://user-images.githubusercontent.com/5393487/39205115-6c3134f6-47bf-11e8-927e-25a8f206f45e.png)

----------

![captura de pantalla 2018-04-24 a la s 12 53 53](https://user-images.githubusercontent.com/5393487/39205717-1807e62a-47c1-11e8-85c5-c3200953c8b6.png)


I have never working with any Google API, super newbie on this. But thanks for the help!

**Comment by Edujugon** [comment]
Hey @CarlosSR ,

Could you paste here also the code snippet ?

**Comment by Edujugon** [comment]
I can see the same error message:
"QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED"

Make sure you're using the correct credentials :)

**Comment by CarlosSR** [comment]
Yeah, I know jaja that was another try, but the good one is all rest of responses. As you can see, it returns us some info but... you know? it happens that I'm connected to another account, should be mine, but no the one of my manager, for some reason I have no permission, but we are working on that. Thanks a lot for reading!

**Comment by Edujugon** [comment]
Hey @CarlosSR ,

No problem, just let me know if you can't get the expected data or face any further issue..
