### ISSUE TITLE
App\Http\Controllers\AdGroupAdService' is not available. Please pass a valid service

### ISSUE THREAD

**Issue by Khalid12345678** [Edujugon/laravel-google-ads#27]
I am using this package i got some following error
My code:-
![image](https://user-images.githubusercontent.com/35664838/43581291-10ad808e-9676-11e8-8ec8-28e8e23f3b14.png)
Error:-
![image](https://user-images.githubusercontent.com/35664838/43581273-fd8ffcde-9675-11e8-9aa6-116db6d02430.png)

Suggest me how to remove this error

**Comment by Edujugon** [comment]
Hi @Khalid12345678 ,

Have a look at this [solved issue](https://github.com/Edujugon/laravel-google-ads/issues/4).

Let me know if that helped

**Comment by Khalid12345678** [comment]
Yes its working fine now.....Thank you so much

**Comment by Khalid12345678** [comment]
How to find credential(developerToken,clientId,clientSecret,refreshToken)
for implementing google adwords api and what is the process?  Is it working
on localhost??

**Comment by Khalid12345678** [comment]
After executing following code:-
![image](https://user-images.githubusercontent.com/35664838/43625289-d186bc92-9709-11e8-970a-c51dbbc7d75c.png)

I am getting following result:-
![image](https://user-images.githubusercontent.com/35664838/43625271-bd5e8074-9709-11e8-8a15-3b29cb261068.png)
I am working on localhost...when i am trying to execute following code for fetching campaigns 
![image](https://user-images.githubusercontent.com/35664838/43625412-9df27460-970a-11e8-8e2f-5e6f61a4d3be.png)
I am getting following errors
![image](https://user-images.githubusercontent.com/35664838/43625432-aef11c80-970a-11e8-9551-b02fd54d1c31.png)

**Comment by Khalid12345678** [comment]
![image](https://user-images.githubusercontent.com/35664838/43625745-3bc7eb10-970c-11e8-8cb0-baa01ada2c18.png)
Ho to get code which is enter in the terminal

**Comment by DzinPerformmaOnline** [comment]
Did you apply for Basic Access in Google ads API?

**Comment by Khalid12345678** [comment]
How to apply??

**Comment by DzinPerformmaOnline** [comment]
Go to your MCC account, click on Tools->API Central and Access Level.

**Comment by DzinPerformmaOnline** [comment]
I looked into your project and the clientCustomerID should be your Adwords Account ID which looks like xxx-xxx-xxxx

**Comment by Khalid12345678** [comment]
It is my google-ads.php
![image](https://user-images.githubusercontent.com/35664838/43773135-53ac1680-9a62-11e8-8993-96346722c26a.png)

Facing same problem 
Can you give me any video reference.I am stuck.
I am facing problems in getting credential.
I am using developer token which is in following image
![image](https://user-images.githubusercontent.com/35664838/43773269-d64a7078-9a62-11e8-8c7b-31459ba91622.png)
I don't know how to fill AdWords API Token Application. 
I am using following client Id and client secret 
![image](https://user-images.githubusercontent.com/35664838/43773524-9dd8ca0e-9a63-11e8-92f5-3ce078e9c7cc.png)

**Comment by Edujugon** [comment]
Hi @Khalid12345678 

I'm assuming this issue has been solved since you opened different issues already using the package.

I'm closing it for now. Feel free to repoen it if required
