### ISSUE TITLE
Upgrade to Google API v37.1.0?

### ISSUE THREAD

**Issue by giv13** [Edujugon/laravel-google-ads#30]
Hi, thank you for the great job.
Do you plan to upgrade the requirements to the latest googleads-php-lib version v37.1.0 (201809)?

**Comment by Edujugon** [comment]
Hi @giv13 ,

Thanks for your message.

Yes, I'll upgrade the googleads dependency to its latest version as soon as I get some free time.
I can not provide an ETA but I'll keep this issue opened and update it once it's done.

**Comment by Edujugon** [comment]
Hi @giv13 ,

I've just updated the package with the lastest google ad version.

Hope this helps :)

**Comment by giv13** [comment]
Many thanks! But I found one mistake. In file `src/Reports/Format.php` in row 14 from `use Google\AdsApi\AdWords\Reporting\v201710\DownloadFormat;` to `use Google\AdsApi\AdWords\Reporting\v201809\DownloadFormat;`

**Comment by Edujugon** [comment]
Closing this issue.
Feel free to open it back if needed.
