### ISSUE TITLE
Not getting campaign list

### ISSUE THREAD

**Issue by Khalid12345678** [Edujugon/laravel-google-ads#32]
I am trying to fetch campaign by using following code.
![screenshot from 2018-10-10 14-56-29](https://user-images.githubusercontent.com/35664838/46726937-18096200-cc9d-11e8-884e-b992dd42b0b7.png)
I am getting following response after using the above code for fetching campaigns. It does not show details of campaigns list. How can I fetch proper campaign list please guide me.
![screenshot_2018-10-10 screenshot](https://user-images.githubusercontent.com/35664838/46726962-28b9d800-cc9d-11e8-8f59-d59f14b86430.png)

**Comment by Edujugon** [comment]
Hi @Khalid12345678 ,

Notice that the get method returns an instance of ServiceCollection.
Just call `items()` method and it will return an Illuminate\Support\Collection so now on you can use it as a any other collection.

**Comment by Khalid12345678** [comment]
Can you write needed code here so that I can check?

**Comment by Edujugon** [comment]
So based on your code you can access the items collection like this:
```php
$items = $list->items();

// From here you have all collection methods available

// For instance, you wanna convert it as plain array:
$items->toArray();
```

Hope the above examples helps.

**Comment by Khalid12345678** [comment]
Thank you @Edujugon

**Comment by Khalid12345678** [comment]
Hello @Edujugon,
I am trying to generate a new refresh token but getting following error.
![c_users_tarun_appdata_local_packages_microsoft skypeapp_kzf8qxf38zg5c_localstate_ee4862f5-2a51-4605-9fae-c0044440e41a](https://user-images.githubusercontent.com/35664838/46736170-f799d180-ccb5-11e8-892b-d538bc64c303.jpg)

**Comment by Edujugon** [comment]
It seems like the response of the fetchAuthtoken is returning something without `refresh_token`. Such key was expected to be in there...

I will update the code to handle that error and be more descriptive on that message...
Anyway, I don't have free time for that right now. I will update this thread as soon as it's done.

**Comment by Edujugon** [comment]
Hi @Khalid12345678 ,

I've been trying to generate a new refresh token and it works as expected. I couldn't reproduce the above issue.

Anyway I released a new package version which will handle that error and output the response in order to see what's going on.

Hope this helps!

**Comment by Khalid12345678** [comment]
Thank you @Edujugon

**Comment by sanjayacloud** [comment]
We have been using your edujugon/laravel-google-ads in order to develop an application to retrieve google AdWords data about campaigns. So far your package and documentation have been of great help. But for some reason, we are unable to get the available campaign data from our ad manager account. We used the default code on the documentation to retrieve the data. 
We would like to know if there is a workaround to overcome this problem. 

` $ads = new GoogleAds();
        $ads->service(CampaignService::class)
            ->select(['Id', 'Name', 'Status', 'ServingStatus', 'StartDate', 'EndDate'])
            ->where('Id = 78796897418')
            ->get();
        dd($ads);`
