### ISSUE TITLE
error

### ISSUE THREAD

**Issue by laravelcoder** [Edujugon/laravel-google-ads#36]
can you tell me how to fix this error please

Error: redirect_uri_mismatch

The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type. You can create a Client ID for native application at https://console.developers.google.com/apis/credentials/oaut

i am trying to make the connection on my local dev but when i try it returns this error.

what am i missing

**Comment by laravelcoder** [comment]
I will do that but now i have a new error

Class Google\AdsApi\AdWords\Reporting\v201710\DownloadFormat does not exist

**Comment by Edujugon** [comment]
What package version are you using?

**Comment by laravelcoder** [comment]
The package is updated to your newest and running on laravel 5.7
with  latest googleads-php-lib version v37.1.0 (201809)

the developer token gets through just fine but no matter what we try we
cannot get anything to return. can you provide a easy code snippet to get
something to return we can put in out controller to make sure its working
correctly please.
any help would be appreciated. or if you know of a repo that is
successfully working on pulling the data and showing it that we can look at
for reference that would even be better.

any help is appreciated your package seems to have great possibility if we
can get it to work.

thank you
phillip

**Comment by Edujugon** [comment]
Hi @laravelcoder ,

Based on the error you reported I would say you've not pulled in the latest version since that error was fixed already. You can see so [here](https://github.com/Edujugon/laravel-google-ads/compare/1.6.0...master#diff-75c166d35d989b218c5e4d336d150598).

Please update the to the latest version and try again.
