### ISSUE TITLE
Client error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `400 Bad Request` response: { "error": "invalid_grant", "error_description": "Bad Request" }

### ISSUE THREAD

**Issue by hichamuim** [Edujugon/laravel-google-ads#5]
Hello,

$ads = new GoogleAds();
$ads->service(CampaignService::class);

I Get This Error

> Client error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `400 Bad Request` response: { "error": "invalid_grant", "error_description": "Bad Request" }

**Comment by Edujugon** [comment]
Hi @hichamuim 
Did you generate the refresh token?

**Comment by hichamuim** [comment]
Hello,
yes i generated using the command :)
thank you so much

2017-09-17 18:06 GMT+01:00 Eduardo Marcos <notifications@github.com>:

**Comment by Edujugon** [comment]
Hi @hichamuim 
Glad to know that worked for you.

I'm now closing this issue.
