### ISSUE TITLE
Error require googleabs dev-master

### ISSUE THREAD

**Issue by unity008** [Edujugon/laravel-google-ads#8]
i get an error, after install  via composer

Problem 1
    - Installation request for edujugon/laravel-google-ads dev-master -> satisfiable by edujugon/laravel-google-ads[dev-master].
    - edujugon/laravel-google-ads dev-master requires googleads/googleads-php-lib ^31.0 -> satisfiable by googleads/googleads-php-lib[31.0.0].
    - Conclusion: don't install phpdocumentor/reflection-docblock 4.x-dev
    - googleads/googleads-php-lib 31.0.0 requires phpdocumentor/reflection-docblock ^3.0.3 -> satisfiable by phpdocumentor/reflection-docblock[3.0.3, 3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0, 3.3.2].
    - Can only install one of: phpdocumentor/reflection-docblock[3.0.3, 4.x-dev].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.0, 4.x-dev].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.1, 4.x-dev].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.0, 4.x-dev].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.1, 4.x-dev].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.2, 4.x-dev].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.3, 4.x-dev].
    - Can only install one of: phpdocumentor/reflection-docblock[3.3.0, 4.x-dev].
    - Can only install one of: phpdocumentor/reflection-docblock[3.3.2, 4.x-dev].
    - Installation request for phpdocumentor/reflection-docblock (locked at 4.x-dev) -> satisfiable by phpdocumentor/reflection-docblock[4.x-dev].

**Comment by Edujugon** [comment]
Hi @unity008 ,
Could you paste here your require section in your project composer.json?

**Comment by Edujugon** [comment]
Hi @unity008 ,

Since I haven't got any response from your end, I understand that you were able to fix your issue. Therefore I'm closing this issue.

Feel free to reopen it whenever you need it.
