### ISSUE TITLE
phpdocumentor/reflection-docblock ^3.0.3

### ISSUE THREAD

**Issue by keithslater** [Edujugon/laravel-google-ads#9]
Getting this error

> Problem 1
    - edujugon/laravel-google-ads 1.2.1 requires googleads/googleads-php-lib ^31.0 -> satisfiable by googleads/googleads-php-lib[31.0.0].
    - Installation request for edujugon/laravel-google-ads ^1.2 -> satisfiable by edujugon/laravel-google-ads[1.2.1].
    - Conclusion: remove phpdocumentor/reflection-docblock 4.2.0
    - Conclusion: don't install phpdocumentor/reflection-docblock 4.2.0
    - googleads/googleads-php-lib 31.0.0 requires phpdocumentor/reflection-docblock ^3.0.3 -> satisfiable by phpdocumentor/reflection-docblock[3.0.3, 3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0, 3.3.2].
    - Can only install one of: phpdocumentor/reflection-docblock[3.0.3, 4.2.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.0, 4.2.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.1, 4.2.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.0, 4.2.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.1, 4.2.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.2, 4.2.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.3, 4.2.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.3.0, 4.2.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.3.2, 4.2.0].
    - Installation request for phpdocumentor/reflection-docblock (locked at 4.2.0) -> satisfiable by phpdocumentor/reflection-docblock[4.2.0].

Looks like they have a fix for it - https://github.com/googleads/googleads-php-lib/issues/370

**Comment by Edujugon** [comment]
Hi @keithslater ,
Thank you for reporting it and providing such link. I'm looking at it and I'll update this ticket as soon as possible.

**Comment by Edujugon** [comment]
Hi @keithslater ,
It was easy :) I've released a new version that fixes it.

Just run again ` composer require edujugon/laravel-google-ads`

Let me know if that solved your issue.
Regards

**Comment by keithslater** [comment]
It works, thanks.
